Split symlinked budget PRJ-383
IMIO/imio.project.pst pull request #6
Opened 2020-04-24 11:45 UTC by daggelpop

J'ai ajouté un datagridfield "budget_split" sur les types Action et dérivés.

Les lignes de "split" sont éditables via la vue "budget_split".
Seuls les pourcentages doivent être changés par les utilisateurs.
Tout le reste est géré via la fonction "update_budget_splits" dans le core, déclenché par des event handlers.
La colonne "title" résume le path de l'objet concerné, afin de pouvoir se repérer. 

Les lignes de split sont utilisées au moment du calcul des budgets globalisés (fonction _updateSummarizedFields).
Les montants sont scindés avant d'être stockés sur les annotations des objets parents.

Vu qu'il n'est pas possible de savoir à l'avance quel pourcentage l'utilisateur veut attribuer à chaque élement, une nouvelle (sub)action reçoit par défaut un pourcentage de 100%, tandis qu'un nouveau (sub)actionlink est fixé à 0 %.

To do:
- ajouter un bouton pour les IPSTAction, redirigeant vers la vue "budget_split".
  remarque: la vue fonctionne aussi sur les (sub)actionlinks.
- la colonne "title" utilisée sur la vue "bugget_split" peut être améliorée.
  est-ce qu'il y a un moyen de la régler en DISPLAY_MODE sans perdre la valeur ?

2020-04-28 12:01 UTC, sgeulette reviewed
ok pour le code.
Peux-tu rajouter un lien vers la vue dans le viewlet qui indique qu'un élément est lié ?
Pour le display_mode, cela ne fonctionne en effet pas car la vue display du widget ne montre plus un input donc on ne retrouve pas le champ dans les données sousmises.
Le mieux serait de faire un js qui rajoute un readonly à l'input.

2020-05-05 08:28 UTC, sgeulette commented
Ok pour ces derniers changements. On va merger nous-même cet PR car on doit merger une autre avant...

2020-07-10 11:32 UTC, sgeulette requested changes
Je mettrais le nouvel index dans collective.symlink de base. 
à voir aussi s'il ne faut pas ajouter un attribut ou marker interface sur les objets afin de pouvoir gérer plus facilement les viewlets et autre. Si c'est un attribut: même valeur. SI c'est un marqueur, on peut avoir un Source... et un Link...

2020-07-10 11:32 UTC, sgeulette commented on src/imio/project/pst/adapters.py
> +        status = "sym_linked"
La différence entre sym_linked et linked n'est pas assez claire je trouve. J'utiliserais plutôt link, original ou source et void

2020-07-10 11:32 UTC, sgeulette commented on src/imio/project/pst/content/action_link.py
> -            navigation_tree_query={"portal_type": ("pstaction",)},
il faut garder aussi le type sinon tu peux avoir n'importe quel élément ici ?

2020-07-17 09:51 UTC, fngaha commented on src/imio/project/pst/adapters.py
> +        status = "sym_linked"
Done

2020-07-17 09:52 UTC, fngaha commented on src/imio/project/pst/content/action_link.py
> -            navigation_tree_query={"portal_type": ("pstaction",)},
Done

2020-07-22 08:37 UTC, sgeulette approved these changes

2020-07-22 08:42 UTC, merged