Moved export / import functionality from core to pst
IMIO/imio.project.pst pull request #7
Opened 2020-05-18 14:00 UTC by fngaha

PRJ-427

2020-05-20 09:47 UTC, sgeulette requested changes

2020-05-20 09:47 UTC, sgeulette commented on src/imio/project/pst/profiles/default/rolemap.xml
> +   <role name="Contributor"/>
en mettant juste Contributor, admin n'est pas dedans.
Je préfère mettre cette attribution dans une migration et non pas en xml.
Mets cela dans le migrate_1_3_1 avec aussi le rechargement de actions.xml

2020-05-25 14:04 UTC, fngaha commented on src/imio/project/pst/profiles/default/rolemap.xml
> +   <role name="Contributor"/>
En effet Stéf j'y ai rajouté Manager, je pense qu'avec cette nouvelle solution la migration n'est pas nécessaire. Il suffit de relancer l'instance

2020-05-27 06:23 UTC, sgeulette requested changes

2020-05-27 06:23 UTC, sgeulette commented on src/imio/project/pst/migrations/migrate_to_1_3_1.py
> +        self.portal.manage_permission('imio.project.pst: ecomptes import', ('Manager', 'Contributor'), acquire=0)
il manque juste aussi 'Site Administrator' à chaque fois.

2020-05-27 17:39 UTC, fngaha commented on src/imio/project/pst/migrations/migrate_to_1_3_1.py
> +        self.portal.manage_permission('imio.project.pst: ecomptes import', ('Manager', 'Contributor'), acquire=0)
En effet stéf, je suis allé trop vite. Voilà

2020-05-28 06:55 UTC, sgeulette approved these changes

2020-05-28 06:56 UTC, merged